package it.gov.pagopa.payhub.activities.service.classifications;

import it.gov.pagopa.payhub.activities.dto.treasury.TreasuryIuf;
import it.gov.pagopa.payhub.activities.service.classifications.trclassifiers.TransferClassifier;
import it.gov.pagopa.pu.classification.dto.generated.ClassificationsEnum;
import it.gov.pagopa.pu.classification.dto.generated.PaymentNotificationNoPII;
import it.gov.pagopa.pu.classification.dto.generated.PaymentsReporting;
import it.gov.pagopa.pu.debtposition.dto.generated.InstallmentNoPII;
import it.gov.pagopa.pu.debtposition.dto.generated.Transfer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Objects;

/**
 * Service for classifying a transfer based on receipt, payment reporting, and treasury data.
 * It uses a list of {@link TransferClassifier} to determine the corresponding labels.
 */
@Lazy
@Slf4j
@Service
public class TransferClassificationService {
	private final List<ClassificationsEnum> defaultClassification = List.of(ClassificationsEnum.UNKNOWN);
	private final List<TransferClassifier> classifiers;

	public TransferClassificationService(List<TransferClassifier> classifiers) {
		this.classifiers = classifiers;
	}

	/**
	 * Determines a list of labels ({@link ClassificationsEnum}) based on the provided data.
	 * <BR />
	 * For each classifier in the list, the {@code define} method is executed with the given parameters.
	 * Non-{@code null} labels are collected into a list. If no classifier produces a valid label,
	 * it will be marked as {@link ClassificationsEnum#UNKNOWN}.
	 *
	 * @param transferDTO the transfer data.
	 * @param installmentDTO the installment data.
	 * @param paymentsReportingDTO the payment reporting data.
	 * @param treasuryIuf the treasury IUF data.
	 * @return a list of valid labels generated by the classifiers.
	 */
	public List<ClassificationsEnum> defineLabels(Transfer transferDTO,
	                                              InstallmentNoPII installmentDTO,
	                                              PaymentNotificationNoPII paymentNotificationDTO,
	                                              PaymentsReporting paymentsReportingDTO,
	                                              TreasuryIuf treasuryIuf) {
		List<ClassificationsEnum> labels = classifiers.stream()
			.map(classifier -> classifier.classify(transferDTO, installmentDTO, paymentNotificationDTO, paymentsReportingDTO, treasuryIuf))
			.filter(Objects::nonNull)
			.toList();

		if (labels.isEmpty()) {
			return defaultClassification;
		}
		return labels;
	}
}
