package it.gov.pagopa.payhub.activities.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class CartDTO implements Serializable {

    private Long cartId;
    private int version;
    private String status; // anagrafica stato
    private String codeAckRp;
    private Date creationDate;
    private Date rpLastUpdateDate;
    private Date rpLastUpdateDateE;
    private String codeSilSendPaymentRequestIdPsp;
    private String codeSilSendPaymentRequestIdBrokerPsp;
    private String codeSilSendPaymentRequestIdChannel;
    private String codeSilSendPaymentRequestIdDomain;
    private String codeSilSendPaymentRequestUniquePaymentId;
    private String codeSilSendPaymentRequestPaymentContextCode;
    private String silSendPaymentRequestOutcome;
    private Integer codeSilSendPaymentRequestRedirect;
    private String codeSilSendPaymentRequestUrl;
    private String codeSilSendPaymentRequestFaultCode;
    private String silSendPaymentRequestFaultString;
    private String codeSilSendPaymentRequestId;
    private String silSendPaymentRequestDescription;
    private Integer codeSilSendPaymentRequestSerial;
    private String rpObjectVersion;
    private String rpDomainId;
    private String applicantStationId;
    private String messageRequest;
    private Date messageRequestDate;
    private String authenticationSubject;
    private Character remitterPaymentRequestUniqueType;
    private byte [] remitterPaymentRequestUniqueIdHash;
    private Character payerPaymentRequestUniqueType;
    private byte [] payerPaymentRequestUniqueIdHash;
    private Date paymentExecutionDate;
    private BigDecimal totalAmountToPay;
    private String paymentType;
    private String rpUniquePaymentId;
    private String remitterPaymentContextCode;
    private String remitterDebitIban;
    private String remitterDebitBIC;
    private String silSendOutcomeNameId;
    private String silSendOutcomePaymentId;
    private String silSendOutcomePaymentContext;
    private String silSendOutcome;
    private String silSendOutcomeFaultCode;
    private String silSendOutcomeFaultString;
    private String silSendOutcomeCode;
    private String silSendOutcomeDescription;
    private Integer silSendOutcomeSerial;
    private String objectVersionO;
    private String domainCode;
    private String requestingStationCode;
    private String receiptMessageId;
    private Date receiptMessageDate;
    private String requestMessageRef;
    private Date requestMessageRefDate;
    private Character attestingInstituteUniqueCodeId;
    private String attestingInstituteUniqueCode;
    private String attestingInstituteName;
    private String attestingInstituteUnitOperator;
    private String attestingInstituteUnitOperatorName;
    private String attestingInstituteAddress;
    private String attestingInstituteCivic;
    private String attestingInstitutePostalCode;
    private String attestingInstituteLocation;
    private String attestingInstituteProvince;
    private String attestingInstituteNation;
    private Character beneficiaryOrgTypeId;
    private String beneficiaryOrgUniqueCode;
    private String beneficiaryOrgName;
    private String beneficiaryOrgCodeUnitOperator;
    private String beneficiaryOrgCodeUnitOperatorName;
    private String beneficiaryOrgAddress;
    private String beneficiaryOrgCivic;
    private String beneficiaryOrgPostalCode;
    private String beneficiaryOrgLocation;
    private String beneficiaryOrgProvince;
    private String beneficiaryOrgNation;
    private Character remitterIdUniqueType;
    private Character payerIdUniqueType;
    private Character payerPaymentOutcomeCode;
    private BigDecimal totalPaidAmount;
    private String payerUniquePaymentId;
    private String payerPaymentContextCode;
    private String idSession;
    private String idSessionFesp;
    private String cartType;
    private Integer paymentModel;
    private String orgSilPaymentResponseUrl;
    private Boolean flagNotificationOutcome;
    private CartMultiBeneficiaryDTO cartMultiBeneficiary;
    private String silSendRpOriginalFaultCode;
    private String silSendRpOriginalFaultString;
    private String silSendRpOriginalFaultDescription;
    private String silSendOutcomeOriginalFaultCode;
    private String silSendOutcomeOriginalFaultString;
    private String silSendOutcomeOriginalFaultDescription;
    private boolean payerEmailNotNull;
    private boolean remitterEmailNotNull;
    private Long personalDataId;
}
