spring:
  config:
    import: mail-templates.yml
  mail:
    host: host
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
activity:
  root:
    path: /DATA/