package it.gov.pagopa.payhub.activities.enums;

public enum EmailTemplateName {
    INGESTION_PAYMENTS_REPORTING_OK,
    INGESTION_PAYMENTS_REPORTING_KO,
    INGESTION_PAYMENTS_REPORTING_PAGOPA_OK,
    INGESTION_PAYMENTS_REPORTING_PAGOPA_KO,

    INGESTION_PAYMENT_NOTIFICATION_OK,
    INGESTION_PAYMENT_NOTIFICATION_KO,

    INGESTION_TREASURY_OPI_OK,
    INGESTION_TREASURY_OPI_KO,

    INGESTION_TREASURY_POSTE_OK,
    INGESTION_TREASURY_POSTE_KO,

    INGESTION_TREASURY_XLS_OK,
    INGESTION_TREASURY_XLS_KO,

    INGESTION_TREASURY_CSV_OK,
    INGESTION_TREASURY_CSV_KO,

    INGESTION_TREASURY_CSV_COMPLETE_OK,
    INGESTION_TREASURY_CSV_COMPLETE_KO,

    INGESTION_DP_INSTALLMENTS_OK,
    INGESTION_DP_INSTALLMENTS_KO,

    INGESTION_PAGOPA_RT,

    INGESTION_ORGANIZATIONS_OK,
    INGESTION_ORGANIZATIONS_KO,

    INGESTION_ORGANIZATIONS_SIL_SERVICE_OK,
    INGESTION_ORGANIZATIONS_SIL_SERVICE_KO,

    INGESTION_DEBT_POSITIONS_TYPE_OK,
    INGESTION_DEBT_POSITIONS_TYPE_KO,

    INGESTION_DEBT_POSITIONS_TYPE_ORG_OK,
    INGESTION_DEBT_POSITIONS_TYPE_ORG_KO,

    INGESTION_DEBT_POSITIONS_TYPE_ORG_OPERATORS_OK,
    INGESTION_DEBT_POSITIONS_TYPE_ORG_OPERATORS_KO,

    INGESTION_ASSESSMENTS_OK,
    INGESTION_ASSESSMENTS_KO,

    INGESTION_ASSESSMENTS_REGISTRY_OK,
    INGESTION_ASSESSMENTS_REGISTRY_KO,

    INGESTION_RECEIPT_OK,
    INGESTION_RECEIPT_KO,

    EXPORT_PAID_OK,
    EXPORT_PAID_KO,

    EXPORT_RECEIPTS_ARCHIVING_OK,
    EXPORT_RECEIPTS_ARCHIVING_KO,

    EXPORT_CLASSIFICATIONS_OK,
    EXPORT_CLASSIFICATIONS_KO
}
