package it.gov.pagopa.payhub.activities.enums;

public enum EmailTemplateName {
    INGESTION_PAYMENTS_REPORTING_OK,
    INGESTION_PAYMENTS_REPORTING_KO,

    INGESTION_TREASURY_OPI_OK,
    INGESTION_TREASURY_OPI_KO,

    INGESTION_DP_INSTALLMENTS_OK,
    INGESTION_DP_INSTALLMENTS_KO,

    INGESTION_PAGOPA_RT
}
