package it.gov.pagopa.payhub.activities.enums;

public enum FileErrorCode {

    //CSV
    CSV_GENERIC_ERROR,
    CSV_MISSING_REQUIRED_FIELD,
    CSV_MISSING_REQUIRED_HEADER,
    CSV_COLUMN_COUNT_MISMATCH,
    CSV_DATA_TYPE_MISMATCH,
    CSV_VALIDATION_ERROR,
    CSV_CONSTRAINT_VIOLATION,

    //XML
    XML_GENERIC_ERROR,
    XML_MISSING_REQUIRED_FIELD,
    XML_VALIDATION_ERROR,
    XML_CONSTRAINT_VIOLATION

}
