name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
      - 'version'

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:

      - name: 🚀 Release with docker action
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/release-action@main #
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_GITHUB_TOKEN_RW }}

      - name: Update application version
        run: echo ${{steps.release.outputs.new_release_version }} > version

      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "p4pa-pagopa-github-bot"
          git add version
          git commit -m "Bump version"
          git push origin ${{ github.ref }}
