name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - P4ADEV-1593_removigDebugActions
#    paths-ignore:
#      - 'CODEOWNERS'
#      - '**.md'
#      - '.**'
#      - 'version'

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:

 #     - name: 🚀 Release with docker action
 #       id: release
 #       uses: pagopa/eng-github-actions-iac-template/global/release-action@main #
 #       with:
 #         github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          fetch-depth: 0

      - name: Update application version
        run: echo 0.0.7-SNAPSHOT > version

      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "p4pa-pagopa-github-bot"
          git add version
          git commit -m "Bump version"
          git config --local remote.origin.url 'https://p4pa-pagopa-github-bot:${{ secrets.ADMIN_GITHUB_TOKEN_RW }}@github.com/pagopa/p4pa-payhub-activities.git'
          git config --local http.https://github.com/.extraheader "AUTHORIZATION: Bearer ${{ secrets.ADMIN_GITHUB_TOKEN_RW }}"
          git config -l
          git push origin P4ADEV-1593_removigDebugActions:main
          #${{ github.ref }}
